<a href="https://colab.research.google.com/github/FelRobG/Respaldos/blob/main/Arreglo_de_2_dims_%2C_3x3_y_valores_diagonales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

arr = np.random.randint(101, size = (3, 3))
print(arr)

#promedio
prom = np.mean(arr)
print("Promedio de los elementos:", prom)

#suma
suma = np.sum(arr)
print("suma de los elementos:", suma)

#maximo
max = np.max(arr)
print("Elemento mayor del arreglo: ", max)

#minimo
min = np.min(arr)
print("Elemento menor del arreglo: ", min)

#diagonal_principal
diag_princ = np.diag(arr)
print("Diagonal principal: ", diag_princ)


[[35 58 78]
 [85 80 60]
 [96 79 55]]
Promedio de los elementos: 69.55555555555556
suma de los elementos: 626
Elemento mayor del arreglo:  96
Elemento menor del arreglo:  35
Diagonal principal:  [35 80 55]
