<a href="https://colab.research.google.com/github/FelRobG/Respaldos/blob/main/Matriz_3x3_ingresada_por_teclado_con_verificacion_de_valor_y_suma_y_repeticion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#func_recorre_y_asigna_val_matriz
def asigna(arreglo):
  i = 0
  j = 0
  while i < 3:
    while j < 3:
      try:
        arreglo[i][j] = int(input(f"Ingrese valor entero de la casilla {[i]}{[j]}:"))
        j += 1
      except(ValueError):
        print("El valor ingresado debe ser un número entero")
    j = 0
    i += 1
  print("Matriz resultante:\n", arreglo)

#suma_y_verif_de_21
def verif_suma(arreglo):
  suma = np.sum(arreglo)
  print("Resultado de la suma de los elementos=", suma)
  if suma == 21:
    print("Suma correcta, el resultado de la suma de las casillas fue 21")
    return True
  else:
    print("Suma incorrecta, el resultado de la suma de las casillas no fue 21")
    return False

###inicio###
while True:
  arreglo = np.zeros((3,3), dtype=int)
  asigna(arreglo)
  if verif_suma(arreglo):
    break

Ingrese valor entero de la casilla [0][0]:1
Ingrese valor entero de la casilla [0][1]:1
Ingrese valor entero de la casilla [0][2]:1
Ingrese valor entero de la casilla [1][0]:1
Ingrese valor entero de la casilla [1][1]:1
Ingrese valor entero de la casilla [1][2]:1
Ingrese valor entero de la casilla [2][0]:1
Ingrese valor entero de la casilla [2][1]:1
Ingrese valor entero de la casilla [2][2]:1
Matriz resultante:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Resultado de la suma de los elementos= 9
Suma incorrecta, el resultado de la suma de casillas  no fue 21
Ingrese valor entero de la casilla [0][0]:2
Ingrese valor entero de la casilla [0][1]:1
Ingrese valor entero de la casilla [0][2]:3
Ingrese valor entero de la casilla [1][0]:2
Ingrese valor entero de la casilla [1][1]:1
Ingrese valor entero de la casilla [1][2]:1
Ingrese valor entero de la casilla [2][0]:1
Ingrese valor entero de la casilla [2][1]:1
Ingrese valor entero de la casilla [2][2]:1
Matriz resultante:
 [[2 1 3]
 [2 1 1]
 [1 1 1]]
Resulta